DbtTestProject:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: 'f7wmxzrdf7fehawekgt4tny6pi-sfoixdf3ksqefe4mb4jqi6bw5a.datawarehouse.pbidedicated.windows.net' # 'SQL Connect String' # 
      port: 1433
      database: WarehouseCedric
      schema: dbo
      
